### ISSUE TITLE
Error occur when installing

### ISSUE THREAD

**Issue by maitnnguyen** [ucl-cssb/sveta#1]
Dear Author,
I clone cneta GitHub to run the model for CNP, when installing, I got the error message:
"""
cnetml.cpp: In function ‘void print_desc(int, int, int, int, int, int, int, int, int)’:
cnetml.cpp:959:10: error: expected ‘;’ before ‘{’ token
  959 |   (model){
      |          ^
      |          ;
make: *** [makefile:24: cnetml] Error 1
"""

I modified the cnetml.cpp file by adding switch before (model) and reinstall with "make". The instalment finished without error message. However, I don't know C++, thus, I am not sure whether I modified correct or not. Can you please help to review it?
Best wishes,

**Comment by icelu** [comment]
Thanks for the interest in the tool.
The errors should have been resolved in the latest version.
